include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # I find it more readable to group dependencies in a meaningful way rather than alphabetically
    sort_pub_dependencies: false
    
    # I find it more readable to group imports in a meaningful way rather than alphabetically
    directives_ordering: false